apiVersion: v1
kind: Secret
metadata:
  name: orange-logistics-secrets
  namespace: orange-logistics
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "orange_logistics_2024"
  MYSQL_USERNAME: "root"
  MYSQL_PASSWORD: "orange_logistics_2024"
  REDIS_PASSWORD: ""
  NACOS_AUTH_TOKEN: "SecretKey012345678901234567890123456789012345678901234567890123456789"
