{{- range $key, $svc := .Values.services }}
{{- if $svc.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $svc.name }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: {{ $svc.name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $svc.port }}
      targetPort: {{ $svc.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ $svc.name }}
{{- end }}
{{- end }}
