apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  namespace: orange-logistics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
        - name: spark-master
          image: apache/spark:3.5.1-java17
          command: ["/opt/spark/bin/spark-class"]
          args: ["org.apache.spark.deploy.master.Master"]
          env:
            - name: SPARK_NO_DAEMONIZE
              value: "true"
            - name: SPARK_MASTER_HOST
              value: "0.0.0.0"
            - name: SPARK_MASTER_PORT
              value: "7077"
            - name: SPARK_MASTER_WEBUI_PORT
              value: "8080"
          ports:
            - containerPort: 7077
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
