services:
  gitlab:
    image: gitlab/gitlab-ce:17.4.0-ce.0
    container_name: gitlab
    hostname: gitlab.local
    restart: unless-stopped
    privileged: true
    ports:
      - "8929:8929"
      - "8922:22"
      - "5050:5050"
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 8922
        puma['worker_processes'] = 2
        sidekiq['max_concurrency'] = 5
        prometheus_monitoring['enable'] = false
        alertmanager['enable'] = false
        gitlab_kas['enable'] = false
        registry['enable'] = true
        registry_external_url 'http://localhost:5050'
        registry['registry_http_addr'] = "0.0.0.0:5050"
    shm_size: '256m'

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: unless-stopped
    volumes:
      - runner_config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - gitlab

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
  runner_config:
